
#version: "3.8"
 
#services:
#localstack:
#   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_cloud}"
   #image: algumaOrigemQueVocePrefira/localstack
   #    image: localstack/localstack
   #network_mode: bridge
   #ports:
   #  - "127.0.0.1:53:53"                # only required for Pro
   #  - "127.0.0.1:53:53/udp"            # only required for Pro
   #  - "127.0.0.1:443:443"              # only required for Pro
   #  - "127.0.0.1:4510-4530:4510-4530"
   #  - "127.0.0.1:4566:4566"
   #  - "127.0.0.1:4571:4571"
   #environment:
   #  - AWS_DEFAULT_REGION=sa-east-1
   #  - AWS_ACCESS_KEY_ID=fakeAccessKeyId
   #  - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
   #  - DEFAULT_REGION=sa-east-1
   #  - http_proxy=
   #  - https_proxy=
   #  - SERVICES=${SERVICES-}
   #  - DEBUG=${DEBUG-}
   #  - DATA_DIR=${DATA_DIR-}
   #  - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
   #  - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
   #  - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
   #  - DOCKER_HOST=unix:///var/run/docker.sock
   #volumes:
   #  - "#${TMPDIR:-/tmp}/localstack:/tmp/localstack"
        #- "/var/run/docker.sock:/var/run/docker.sock"
        #
        #

version: "3.8"

services:

  microservice1:
    container_name: microservice1
    image: microservice1
    build:
      context: ./microservico1
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  microservice2:
    container_name: microservice2
    image: microservice2
    build:
      context: ./microservico2
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - localstack
    environment:
      - AWS_ENDPOINT=http://localstack:4566
    networks:
      - app-network
  
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge